apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: dopplersecret-quizlord-api-secret # DopplerSecret Name
  namespace: doppler-operator-system
spec:
  tokenSecret: # Kubernetes service token secret (namespace defaults to doppler-operator-system)
    name: doppler-token-quizlord-api-secret
  managedSecret: # Kubernetes managed secret (will be created if does not exist)
    name: doppler-quizlord-api-secret
    namespace: quizlord # Should match the namespace of deployments that will use the secret
