services:
  postgres:
    container_name: quizlord-postgres
    image: postgres:17
    ports:
      - 15432:5432
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=local
    volumes:
      - ./scripts/init-script.sql:/docker-entrypoint-initdb.d/init-script.sql
