# This workflow publishes the Docker image to the GitHub Container Registry and the Helm chart to the appropriate s3 bucket.
# It's triggered when a new tag is pushed to the repository, this can either be in main (as a release tag) or in a feature 
# branch (as a prerelease tag).

name: Publish

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"

# Note this alone is not enough to give the action write access
# In the registry settings https://github.com/users/danielemery/packages/container/quizlord-api/settings
# you must also add the action with write access under Manage actions access
permissions:
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  NODE_VERSION: 18.17.1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install packages
        run: npm ci

      - name: Build
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: |
            dist
            prisma
            Dockerfile
            .dockerignore
            package*.json

      - name: Upload helm chart
        uses: actions/upload-artifact@v3
        with:
          name: helm-chart
          path: helm

  docker-publish:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  helm-publish:
    needs:
      - build
      - docker-publish
    runs-on: ubuntu-latest
    container:
      image: hypnoglow/helm-s3:master-helm3.11
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.HELM_DEPLOY_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.HELM_DEPLOY_SECRET }}
        AWS_DEFAULT_REGION: $${{ vars.HELM_DEPLOY_REGION }}

    steps:
      - name: Download chart definition
        uses: actions/download-artifact@v3
        with:
          name: helm-chart

      - name: Add repo
        run: |
          helm repo add demery-s3 s3://helm.demery.net
          helm repo list

      - name: Package chart
        run: |
          helm package ./helm --version=${{ github.ref_name }} --app-version=${{ github.ref_name }}

      - name: Publish chart
        run: |
          helm s3 push --relative ./quizlord-api-${{ github.ref_name }}.tgz demery-s3
